services:
  telemetry-db:
    image: postgres:17.2
    restart: always
    volumes:
      - telemetry-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${TELEMETRY_DB_USER:?TELEMETRY_DB_USER is not set}
      POSTGRES_PASSWORD: ${TELEMETRY_DB_PASSWORD:?TELEMETRY_DB_PASSWORD is not set}
      POSTGRES_DB: ${TELEMETRY_DB:?TELEMETRY_DB is not set}

volumes:
  telemetry-db: