services:
  image_service:
      image: ghcr.io/${org}/image-service:${IMAGE_SERVICE_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
      restart: always
      environment:
        IMAGE_SERVICE_WEAVIATE_HTTP_HOST: ${IMAGE_SERVICE_WEAVIATE_HTTP_HOST:?IMAGE_SERVICE_WEAVIATE_HTTP_HOST is not set}
        IMAGE_SERVICE_WEAVIATE_HTTP_PORT: ${IMAGE_SERVICE_WEAVIATE_HTTP_PORT:?IMAGE_SERVICE_WEAVIATE_HTTP_PORT is not set}
        IMAGE_SERVICE_WEAVIATE_HTTP_SECURE: ${IMAGE_SERVICE_WEAVIATE_HTTP_SECURE:?IMAGE_SERVICE_WEAVIATE_HTTP_SECURE is not set}
        IMAGE_SERVICE_WEAVIATE_GRPC_HOST: ${IMAGE_SERVICE_WEAVIATE_GRPC_HOST:?IMAGE_SERVICE_WEAVIATE_GRPC_HOST is not set}
        IMAGE_SERVICE_WEAVIATE_GRPC_PORT: ${IMAGE_SERVICE_WEAVIATE_GRPC_PORT:?IMAGE_SERVICE_WEAVIATE_GRPC_PORT is not set}
        IMAGE_SERVICE_WEAVIATE_GRPC_SECURE: ${IMAGE_SERVICE_WEAVIATE_GRPC_SECURE:?IMAGE_SERVICE_WEAVIATE_GRPC_SECURE is not set}
        IMAGE_SERVICE_BUCKET_NAME: ${IMAGE_SERVICE_BUCKET_NAME:?IMAGE_SERVICE_BUCKET_NAME is not set}
        IMAGE_SERVICE_MINIO_ENDPOINT: ${IMAGE_SERVICE_MINIO_ENDPOINT:?IMAGE_SERVICE_MINIO_ENDPOINT is not set}
        IMAGE_SERVICE_MINIO_ACCESS_KEY: ${IMAGE_SERVICE_MINIO_ACCESS_KEY:?IMAGE_SERVICE_MINIO_ACCESS_KEY is not set}
        IMAGE_SERVICE_MINIO_SECRET_KEY: ${IMAGE_SERVICE_MINIO_SECRET_KEY:?IMAGE_SERVICE_MINIO_SECRET_KEY is not set}
        IMAGE_SERVICE_USE_SSL: ${IMAGE_SERVICE_USE_SSL:?IMAGE_SERVICE_USE_SSL is not set} 
