services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      WAVIATE_QUERY_DEFAULTS_LIMIT: ${WAVIATE_QUERY_DEFAULTS_LIMIT:?WAVIATE_QUERY_DEFAULTS_LIMIT is not set}
      WAVIATE_AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: ${WAVIATE_AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED:?WAVIATE_AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED is not set}
      WAVIATE_PERSISTENCE_DATA_PATH: ${WAVIATE_PERSISTENCE_DATA_PATH:?WAVIATE_PERSISTENCE_DATA_PATH is not set}
      WAVIATE_DEFAULT_VECTORIZER_MODULE: ${WAVIATE_DEFAULT_VECTORIZER_MODULE:?WAVIATE_DEFAULT_VECTORIZER_MODULE is not set}
      WAVIATE_ENABLE_MODULES: ${WAVIATE_ENABLE_MODULES:?WAVIATE_ENABLE_MODULES is not set}
      WAVIATE_CLUSTER_HOSTNAME: ${WAVIATE_CLUSTER_HOSTNAME:?WAVIATE_CLUSTER_HOSTNAME is not set}
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: always

volumes:
  weaviate_data: