services:
  epic_global_backend:
      image: ghcr.io/${org}/epic-global-backend:${EPIC_GLOBAL_BACKEND_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
      restart: always
      environment:
<<<<<<< HEAD
        DB_HOST: ${DB_HOST:?DB_HOST is not set}
        DB_NAME: ${DB_NAME:?DB_NAME is not set}
        DB_USER: ${DB_USER:?DB_USER is not set}
        DB_PASS: ${DB_PASS:?DB_PASS is not set}
        DATABASE_URL: ${DATABASE_URL:?DATABASE_URL is not set}
        CACHE_HOST: ${CACHE_HOST:?CACHE_HOST is not set}
        CACHE_PORT: ${CACHE_PORT:?CACHE_PORT is not set}
        MINIO_ENDPOINT: ${MINIO_ENDPOINT:?MINIO_ENDPOINT is not set}
        MINIO_USE_SSL: ${MINIO_USE_SSL:?MINIO_USE_SSL is not set}
        MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME:?MINIO_BUCKET_NAME is not set}
        MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:?MINIO_BUCKET_NAME is not set}
        MAX_FILES_TO_UPLOAD: ${MAX_FILES_TO_UPLOAD:?MINIO_BUCKET_NAME is not set}
        API_BASE_URL: ${API_BASE_URL:?MINIO_BUCKET_NAME is not set}
        AMAZON_CLIENT_ID: ${AMAZON_CLIENT_ID:?AMAZON_CLIENT_ID is not set}
        AMAZON_CLIENT_SECRET: ${AMAZON_CLIENT_SECRET:?AMAZON_CLIENT_SECRET is not set}
        AMAZON_REFRESH_TOKEN: ${AMAZON_REFRESH_TOKEN:?AMAZON_REFRESH_TOKEN is not set}
        PRODUCT_LISTING_BASE_URL: ${PRODUCT_LISTING_BASE_URL:?PRODUCT_LISTING_BASE_URL is not set}
        AI_SERVICE_BASE_URL: ${AI_SERVICE_BASE_URL:?AI_SERVICE_BASE_URL is not set}
        KEYCLOAK_HOST_URL: ${KEYCLOAK_HOST_URL:?KEYCLOAK_HOST_URL is not set}
        KEYCLOAK_REALM: ${KEYCLOAK_REALM:?KEYCLOAK_REALM is not set}
        KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID:?KEYCLOAK_CLIENT_ID is not set}
        KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET:?KEYCLOAK_CLIENT_SECRET is not set}
        WALMART_CLIENT_ID: ${WALMART_CLIENT_ID:?WALMART_CLIENT_ID is not set}
        WALMART_CLIENT_SECRET: ${WALMART_CLIENT_SECRET:?WALMART_CLIENT_SECRET is not set}
        WALMART_CHANNEL_ID: ${WALMART_CHANNEL_ID:?WALMART_CHANNEL_ID is not set}
        KEYCLOAK_CLIENT_UUID: ${KEYCLOAK_CLIENT_UUID:?KEYCLOAK_CLIENT_UUID is not set}
        KEYCLOAK_ROLE_UUID: ${KEYCLOAK_ROLE_UUID:?KEYCLOAK_ROLE_UUID is not set}
        DOCS_PASSWORD: ${DOCS_PASSWORD:?DOCS_PASSWORD is not set}
        COUPANG_ACCESS_KEY: ${COUPANG_ACCESS_KEY:?COUPANG_ACCESS_KEY is not set}
        COUPANG_SECRET_KEY: ${COUPANG_SECRET_KEY:?COUPANG_SECRET_KEY is not set}
        COUPANG_VENDOR_ID: ${COUPANG_VENDOR_ID:?COUPANG_VENDOR_ID is not set}
        COUPANG_VENDOR_USER_ID: ${COUPANG_VENDOR_USER_ID:?COUPANG_VENDOR_USER_ID is not set}
=======
        BACKEND_SERVICE_DATABASE_URL: ${BACKEND_SERVICE_DATABASE_URL:?BACKEND_SERVICE_DATABASE_URL is not set}
        BACKEND_SERVICE_CACHE_HOST: ${BACKEND_SERVICE_CACHE_HOST:?BACKEND_SERVICE_CACHE_HOST is not set}
        BACKEND_SERVICE_CACHE_PORT: ${BACKEND_SERVICE_CACHE_PORT:?BACKEND_SERVICE_CACHE_PORT is not set}
        BACKEND_SERVICE_MINIO_ENDPOINT: ${BACKEND_SERVICE_MINIO_ENDPOINT:?BACKEND_SERVICE_MINIO_ENDPOINT is not set}
        BACKEND_SERVICE_MINIO_USE_SSL: ${BACKEND_SERVICE_MINIO_USE_SSL:?BACKEND_SERVICE_MINIO_USE_SSL is not set}
        BACKEND_SERVICE_MINIO_BUCKET_NAME: ${BACKEND_SERVICE_MINIO_BUCKET_NAME:?BACKEND_SERVICE_MINIO_BUCKET_NAME is not set}
        BACKEND_SERVICE_MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:?BACKEND_SERVICE_MINIO_ACCESS_KEY is not set}
        BACKEND_SERVICE_MAX_FILES_TO_UPLOAD: ${BACKEND_SERVICE_MAX_FILES_TO_UPLOAD:?BACKEND_SERVICE_MAX_FILES_TO_UPLOAD is not set}
        BACKEND_SERVICE_SKU_REGISTRY_BASE_URL: ${BACKEND_SERVICE_SKU_REGISTRY_BASE_URL:?BACKEND_SERVICE_SKU_REGISTRY_BASE_URL is not set}
        BACKEND_SERVICE_SKU_LISTING_BASE_URL: ${BACKEND_SERVICE_SKU_LISTING_BASE_URL:?BACKEND_SERVICE_SKU_LISTING_BASE_URL is not set}
        BACKEND_SERVICE_AI_SERVICE_BASE_URL: ${BACKEND_SERVICE_AI_SERVICE_BASE_URL:?BACKEND_SERVICE_AI_SERVICE_BASE_URL is not set}
        BACKEND_SERVICE_AUTH_SERVICE_BASE_URL: ${BACKEND_SERVICE_AUTH_SERVICE_BASE_URL:?BACKEND_SERVICE_AUTH_SERVICE_BASE_URL is not set}
        BACKEND_SERVICE_KEYCLOAK_HOST_URL: ${BACKEND_SERVICE_KEYCLOAK_HOST_URL:?BACKEND_SERVICE_KEYCLOAK_HOST_URL is not set}
        BACKEND_SERVICE_KEYCLOAK_REALM: ${BACKEND_SERVICE_KEYCLOAK_REALM:?BACKEND_SERVICE_KEYCLOAK_REALM is not set}
        BACKEND_SERVICE_KEYCLOAK_CLIENT_ID: ${BACKEND_SERVICE_KEYCLOAK_CLIENT_ID:?BACKEND_SERVICE_KEYCLOAK_CLIENT_ID is not set}
        BACKEND_SERVICE_KEYCLOAK_CLIENT_SECRET: ${BACKEND_SERVICE_KEYCLOAK_CLIENT_SECRET:?BACKEND_SERVICE_KEYCLOAK_CLIENT_SECRET is not set}
        BACKEND_SERVICE_KEYCLOAK_CLIENT_UUID: ${BACKEND_SERVICE_KEYCLOAK_CLIENT_UUID:?BACKEND_SERVICE_KEYCLOAK_CLIENT_UUID is not set}
        BACKEND_SERVICE_KEYCLOAK_ROLE_UUID: ${BACKEND_SERVICE_KEYCLOAK_ROLE_UUID:?BACKEND_SERVICE_KEYCLOAK_ROLE_UUID is not set}
        BACKEND_SERVICE_DOCS_PASSWORD: ${BACKEND_SERVICE_DOCS_PASSWORD:?BACKEND_SERVICE_DOCS_PASSWORD is not set}
        BACKEND_SERVICE_ESM_AUTH_EMAIL: ${BACKEND_SERVICE_ESM_AUTH_EMAIL:?BACKEND_SERVICE_ESM_AUTH_EMAIL is not set}
        BACKEND_SERVICE_ESM_AUTH_PASSWORD: ${BACKEND_SERVICE_ESM_AUTH_PASSWORD:?BACKEND_SERVICE_ESM_AUTH_PASSWORD is not set}
        BACKEND_SERVICE_CREDENTIALS_ENCRYPTION_KEY: ${BACKEND_SERVICE_CREDENTIALS_ENCRYPTION_KEY:?BACKEND_SERVICE_CREDENTIALS_ENCRYPTION_KEY is not set}
        BACKEND_SERVICE_ASIN_FETCH_COUNTRY: ${BACKEND_SERVICE_ASIN_FETCH_COUNTRY:?BACKEND_SERVICE_ASIN_FETCH_COUNTRY is not set}
        BACKEND_SERVICE_REDIS_PASSWORD: ${BACKEND_SERVICE_REDIS_PASSWORD:?BACKEND_SERVICE_REDIS_PASSWORD is not set}
        BACKEND_SERVICE_REDIS_TLS_ENABLED: ${BACKEND_SERVICE_REDIS_TLS_ENABLED:?BACKEND_SERVICE_REDIS_TLS_ENABLED is not set}
        BACKEND_SERVICE_REDIS_TLS_CA: ${BACKEND_SERVICE_REDIS_TLS_CA:?BACKEND_SERVICE_REDIS_TLS_CA is not set}
        BACKEND_SERVICE_REDIS_HOST: ${BACKEND_SERVICE_REDIS_HOST:?BACKEND_SERVICE_REDIS_HOST is not set}
>>>>>>> main
