services:
  epic_global_backend:
      image: ghcr.io/${org}/epic-global-backend:${DEMO_SERVICE_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
      restart: always
      ports:
        - 3000:3000
      environment:
        DB_HOST: ${DB_HOST:?DB_HOST is not set}
        DB_NAME: ${DB_NAME:?DB_NAME is not set}
        DB_USER: ${DB_USER:?DB_USER is not set}
        DB_PASS: ${DB_PASS:?DB_PASS is not set}
        DATABASE_URL: ${DATABASE_URL:?DATABASE_URL is not set}
        REDIS_HOST: ${REDIS_HOST:?REDIS_HOST is not set}
        REDIS_PORT: ${REDIS_PORT:?REDIS_PORT is not set}
        MINIO_ENDPOINT: ${MINIO_ENDPOINT:?MINIO_ENDPOINT is not set}
        MINIO_PORT: ${MINIO_PORT:?MINIO_PORT is not set}
        MINIO_USE_SSL: ${MINIO_USE_SSL:?MINIO_USE_SSL is not set}
        MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME:?MINIO_BUCKET_NAME is not set}